export const topNav2links = [
    {link: '#', title: 'ABOUT PUP', subLinks: [
        {subLinkTitle: 'University Profile', url: '#'}, 
        {subLinkTitle: 'Vision and Mission', url: '#'}, 
        {subLinkTitle: 'History',url: '#'},
        {subLinkTitle: 'Logo and Symbols',url: '#'},
        {subLinkTitle: 'Hymn',url: '#'},
        {subLinkTitle: 'Annual Reports',url: '#'},
        {subLinkTitle: 'Awards and Recognitions',url: '#'},
        {subLinkTitle: 'Contact us',url: '#'},
        {subLinkTitle: 'Maps',url: '#'},
        {subLinkTitle: 'University Code',url: '#'},
        {subLinkTitle: 'Institutional Development Plan',url: '#'},
        {subLinkTitle: 'Quality Policy Statement',url: '#'},
        {subLinkTitle: 'Branches and Satellite Campuses',url: '#'},
        {subLinkTitle: 'Memorandum Orders',url: '#'},
        {subLinkTitle: 'Strategic Performance Management System',url: '#'},
    ]},
    {link: '#', title: 'ACADEMIC', subLinks: [
        {subLinkTitle: 'Academic Programs',url: '#'},
        {subLinkTitle: 'Open University System',url: '#'},
        {subLinkTitle: 'Graduate Studies',url: '#'},
        {subLinkTitle: 'Colleges',url: '#'},
        {subLinkTitle: 'Institute of Technology',url: '#'},
        {subLinkTitle: 'Senior High School',url: '#'},
        {subLinkTitle: 'Laboratory High SChool',url: '#'},
        {subLinkTitle: 'Library Services',url: '#'},
        {subLinkTitle: 'Online Public Access Catalog',url: '#'},
        {subLinkTitle: 'Quality Assurance',url: '#'},
        {subLinkTitle: 'Teaching and Learning Development',url: '#'},
        {subLinkTitle: 'PUP eMabini Learning Portal',url: '#'},
        {subLinkTitle: 'OVPAA',url: '#'},
    ]},
    {link: '#', title: 'STUDENTS', subLinks: [
        {subLinkTitle: 'Student Services',url: '#'},
        {subLinkTitle: 'Student Organizations',url: '#'},
        {subLinkTitle: 'Student Publications',url: '#'},
        {subLinkTitle: 'Student Council',url: '#'},
        {subLinkTitle: 'Student Handbook',url: '#'},
        {subLinkTitle: 'University Registrar',url: '#'},
        {subLinkTitle: 'PUP Student Information System',url: '#'},
        {subLinkTitle: 'PUP Online Document Request System',url: '#'},
        {subLinkTitle: 'PUP Bookstore',url: '#'},
        {subLinkTitle: 'Downloadable Forms',url: '#'},
        {subLinkTitle: 'Online Job Postings',url: '#'},
    ]},
    {link: '#', title: 'RESEARCH', subLinks: [
        {subLinkTitle: 'Researchers',url: '#'},
        {subLinkTitle: 'Extensions',url: '#'},
        {subLinkTitle: 'Institutional Planning',url: '#'},
        {subLinkTitle: 'Intellectual Property',url: '#'},
        {subLinkTitle: 'Research Publications',url: '#'},
        {subLinkTitle: 'Science and Technology',url: '#'},
        {subLinkTitle: 'Cultural and Language',url: '#'},
        {subLinkTitle: 'Strategic Foresight and Innovation',url: '#'},
        {subLinkTitle: 'Human and Social Development',url: '#'},
        {subLinkTitle: 'Gender and Development',url: '#'},
        {subLinkTitle: 'PUP Online Journal System',url: '#'},
        {subLinkTitle: 'PUP Online Survey for Faculty Evaluation',url: '#'},
        {subLinkTitle: 'University Thesis and Dissertion Manual',url: '#'},
    ]},
]